-- MySQL Script generated by MySQL Workbench
-- Mon Mar  9 16:59:57 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Journal`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Journal` (
  `Journal_ID` INT NOT NULL,
  `Journal_date` DATE NOT NULL,
  `Journal_heure` TIME NOT NULL,
  `Journal_contenu` MEDIUMTEXT NOT NULL,
  `Journal_modification` DATE NOT NULL,
  `Journal_titre` TINYTEXT NOT NULL,
  PRIMARY KEY (`Journal_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tache` (
  `Tache_ID` INT NOT NULL,
  `Tache_date` DATE NOT NULL,
  `Tache_nom` TINYTEXT NOT NULL,
  `Tache_statut` TINYINT(1) NOT NULL,
  `Tache_sous_tache` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Tache_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tracker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tracker` (
  `Tracker_ID` INT NOT NULL,
  `Tracker_nom` TINYTEXT NOT NULL,
  `Tracker_description` MEDIUMTEXT NOT NULL,
  `Tracker_couleur` ENUM("rouge", "orange", "jaune", "vert", "bleu", "violet", "rose") NOT NULL,
  `Tracker_icone` ENUM("rond", "carré", "triangle", "goute", "livre", "lune", "sport", "none") NOT NULL DEFAULT '\"none\"',
  PRIMARY KEY (`Tracker_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calendrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calendrier` (
  `Calendrier_ID` INT NOT NULL,
  `Calendrier_jour` DATE NOT NULL,
  PRIMARY KEY (`Calendrier_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tracker_has_Calendrier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tracker_has_Calendrier` (
  `Tracker_Tracker_ID` INT NOT NULL,
  `Calendrier_Calendrier_ID` INT NOT NULL,
  `Calendrier_has_Tracker_statut` TINYINT(1) NOT NULL,
  PRIMARY KEY (`Tracker_Tracker_ID`, `Calendrier_Calendrier_ID`),
  INDEX `fk_Tracker_has_Calendrier_Calendrier1_idx` (`Calendrier_Calendrier_ID` ASC) VISIBLE,
  INDEX `fk_Tracker_has_Calendrier_Tracker_idx` (`Tracker_Tracker_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Tracker_has_Calendrier_Tracker`
    FOREIGN KEY (`Tracker_Tracker_ID`)
    REFERENCES `mydb`.`Tracker` (`Tracker_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tracker_has_Calendrier_Calendrier1`
    FOREIGN KEY (`Calendrier_Calendrier_ID`)
    REFERENCES `mydb`.`Calendrier` (`Calendrier_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Calendrier_has_Tracker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Calendrier_has_Tracker` (
  `Calendrier_Calendrier_ID` INT NOT NULL,
  `Tracker_Tracker_ID` INT NOT NULL,
  `Calendrier_has_Tracker_Statut` TINYINT(1) NULL,
  PRIMARY KEY (`Calendrier_Calendrier_ID`, `Tracker_Tracker_ID`),
  INDEX `fk_Calendrier_has_Tracker_Tracker1_idx` (`Tracker_Tracker_ID` ASC) VISIBLE,
  INDEX `fk_Calendrier_has_Tracker_Calendrier1_idx` (`Calendrier_Calendrier_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Calendrier_has_Tracker_Calendrier1`
    FOREIGN KEY (`Calendrier_Calendrier_ID`)
    REFERENCES `mydb`.`Calendrier` (`Calendrier_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Calendrier_has_Tracker_Tracker1`
    FOREIGN KEY (`Tracker_Tracker_ID`)
    REFERENCES `mydb`.`Tracker` (`Tracker_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parametres`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parametres` (
  `Parametres_ID` INT NOT NULL,
  `Parametres_affichage` ENUM("Journal", "Tache", "Tracker") NOT NULL DEFAULT '\"Journal\"',
  `Parametres_Couleurs` ENUM("Normal") NOT NULL DEFAULT '\"Normal\"',
  PRIMARY KEY (`Parametres_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sous_Tache`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sous_Tache` (
  `Sous_Tache_ID` INT NOT NULL,
  `Sous_Tache_nom` TINYTEXT NOT NULL,
  `Sous_Tache_statut` TINYINT(1) NOT NULL,
  `Tache_Tache_ID` INT NOT NULL,
  PRIMARY KEY (`Sous_Tache_ID`),
  INDEX `fk_Sous_Tache_Tache1_idx` (`Tache_Tache_ID` ASC) VISIBLE,
  CONSTRAINT `fk_Sous_Tache_Tache1`
    FOREIGN KEY (`Tache_Tache_ID`)
    REFERENCES `mydb`.`Tache` (`Tache_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
